package Interfaz;

import Clases.Usuario2;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Administrador
 */
public class InfLab02 extends javax.swing.JFrame {

    private Usuario2 usuario2;

    public InfLab02() {
        initComponents();
        eliminar.setVisible(false);
        this.setLocationRelativeTo(null);
        usuario2 = new Usuario2();
        usuario2.mostrarUsuarios(mostrarInfo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        ingresoId = new javax.swing.JTextField();
        pdf = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mostrarInfo = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ingresoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoIdActionPerformed(evt);
            }
        });
        jPanel3.add(ingresoId, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 160, -1));

        pdf.setBackground(new java.awt.Color(0, 0, 51));
        pdf.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        pdf.setForeground(new java.awt.Color(255, 255, 255));
        pdf.setText("DESCARGAR REPORTE");
        pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfActionPerformed(evt);
            }
        });
        jPanel3.add(pdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, -1, -1));

        buscar.setBackground(new java.awt.Color(0, 0, 51));
        buscar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        buscar.setForeground(new java.awt.Color(255, 255, 255));
        buscar.setText("BUSCAR");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel3.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, -1, -1));

        regresar.setBackground(new java.awt.Color(0, 0, 51));
        regresar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        regresar.setForeground(new java.awt.Color(255, 255, 255));
        regresar.setText("REGRESAR");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        jPanel3.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, -1));

        actualizar.setBackground(new java.awt.Color(0, 0, 51));
        actualizar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        actualizar.setForeground(new java.awt.Color(255, 255, 255));
        actualizar.setText("ACTUALIZAR");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        jPanel3.add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, -1, -1));

        eliminar.setBackground(new java.awt.Color(255, 51, 51));
        eliminar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        eliminar.setText("ELIMINAR");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel3.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, -1, -1));

        salir.setBackground(new java.awt.Color(0, 0, 51));
        salir.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("SALIR");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel3.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, -1, -1));

        mostrarInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        mostrarInfo.setRowHeight(40);
        mostrarInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(mostrarInfo);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 870, 190));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("INGRESE NOMBRE DEL DOCENTE");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("estudiantes, 1 mesa de trabajo docente.");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("20 computadores completos (CPU ,monitor, teclado, mouse), 1 proyector tiro corto, 20 cables de red, 20 sillas, 8 mesas trabajo");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INFORMACIÓN DEL LABORATORIO 02");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("AYUDA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 80, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/LogoP1.png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Salida.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 910, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        Laboratorio02 regresaLab01 = new Laboratorio02();
        regresaLab01.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresarActionPerformed

    private void mostrarInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarInfoMouseClicked
        // TODO add your handling code here:
        eliminar.setVisible(true);
        //objetoUsuario.Seleccionar(mostrarInfo, materia, null, nombre, null, materia, alumnos, observacion);
    }//GEN-LAST:event_mostrarInfoMouseClicked

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
         int filaSeleccionada = mostrarInfo.getSelectedRow();

        // Verificar si se ha seleccionado alguna fila
        if (filaSeleccionada != -1) {
            // Obtener el valor del ID de la fila seleccionada en la columna 0
            int id = Integer.parseInt(mostrarInfo.getValueAt(filaSeleccionada, 0).toString());

            // Llamar al método Eliminar pasando el ID obtenido
            usuario2.Eliminar(id);
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona una fila para eliminar");
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        // TODO add your handling code here:
        usuario2.mostrarUsuarios(mostrarInfo);
    }//GEN-LAST:event_actualizarActionPerformed

    private void pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfActionPerformed
       // Crear un documento
        Document documento = new Document(PageSize.A4.rotate());

        try {
            // Obtener la ruta del escritorio del usuario
            String ruta = System.getProperty("user.home") + "/Desktop/Reporte_Horario_Lab02.pdf";

            // Crear un escritor PDF
            PdfWriter.getInstance(documento, new FileOutputStream(ruta));
            documento.open();

            // Crear un objeto Paragraph para el título
            Paragraph titulo = new Paragraph("      UNIVERSIDAD DE LAS FUERZAS ARMADAS ESPE", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18));

            // Agregar el título al documento
            documento.add(titulo);
            documento.add(new Paragraph(" "));

            // Crear un objeto Paragraph para la información adicional
            Paragraph infoAdicional = new Paragraph("""
                                            Reporte de Horario
                                            A continuación se entregan las siguientes herramientas:
                                            * 20 computadores completos (CPU, monitor, teclado, mouse).
                                            * 20 cables de red, 20 sillas, 8 mesas trabajo estudiantes.
                                            * 1 proyector tiro corto.
                                            * 1 mesa de trabajo docente.""",
                    FontFactory.getFont(FontFactory.HELVETICA, 12));

            // Agregar la información adicional al documento
            documento.add(infoAdicional);
            // Agregar un espacio en blanco
            documento.add(new Paragraph(" "));

            // Crear una tabla PDF con 7 columnas
            PdfPTable tabla = new PdfPTable(7);
            float[] columnWidths = {6, 20, 20, 15, 20, 18, 18};
            tabla.setWidths(columnWidths);

            // Tamaño de fuente para las celdas de la tabla
            com.itextpdf.text.Font fontCeldas = FontFactory.getFont(FontFactory.HELVETICA, 9);

            // Agregar encabezados de columna a la tabla
            tabla.addCell(new PdfPCell(new Phrase("ID", fontCeldas)));//1
            tabla.addCell(new PdfPCell(new Phrase("FECHA", fontCeldas)));//7
            tabla.addCell(new PdfPCell(new Phrase("HORA", fontCeldas)));//8
            tabla.addCell(new PdfPCell(new Phrase("DOCENTE", fontCeldas)));//2
            tabla.addCell(new PdfPCell(new Phrase("MATERIA", fontCeldas)));//3
            tabla.addCell(new PdfPCell(new Phrase("ALUMNOS", fontCeldas)));//4
            tabla.addCell(new PdfPCell(new Phrase("OBSERVACION", fontCeldas)));//5

            try {
                // Establecer la conexión con la base de datos
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bdDatos", "root", "080210");

                // Preparar la consulta SQL
                PreparedStatement pst = cn.prepareStatement("SELECT * FROM usuarios2 ORDER BY dia, hora");

                // Ejecutar la consulta y obtener los resultados
                ResultSet rs = pst.executeQuery();

                // Iterar sobre los resultados y agregar filas a la tabla PDF
                while (rs.next()) {
                    tabla.addCell(new PdfPCell(new Phrase(rs.getString(1), fontCeldas)));
                    tabla.addCell(new PdfPCell(new Phrase(rs.getString(7), fontCeldas)));
                    tabla.addCell(new PdfPCell(new Phrase(rs.getString(8), fontCeldas)));
                    tabla.addCell(new PdfPCell(new Phrase(rs.getString(2), fontCeldas)));
                    tabla.addCell(new PdfPCell(new Phrase(rs.getString(3), fontCeldas)));
                    tabla.addCell(new PdfPCell(new Phrase(rs.getString(4), fontCeldas)));
                    tabla.addCell(new PdfPCell(new Phrase(rs.getString(5), fontCeldas)));

                }

                // Agregar la tabla al documento
                documento.add(tabla);

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error al ejecutar la consulta SQL");
            } finally {
                // Cerrar el documento al finalizar
                documento.close();
            }

            JOptionPane.showMessageDialog(null, "Reporte creado en: " + ruta);

        } catch (DocumentException | HeadlessException | FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Error al crear el reporte PDF");
        }
    }//GEN-LAST:event_pdfActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // Obtener el nombre ingresado en el campo de texto
    String nombre = ingresoId.getText();

    // Verificar si se ha ingresado un nombre
    if (!nombre.isEmpty()) {
        // Buscar y mostrar la información del usuario por el nombre
        usuario2.buscarUsuarioPorNombre(nombre, mostrarInfo);
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese un nombre.");
    }
    
    // Limpiar el campo de texto después de la búsqueda
    ingresoId.setText("");
    }//GEN-LAST:event_buscarActionPerformed

    private void ingresoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoIdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        helpInfLab02 helpPr2 = new helpInfLab02();
        helpPr2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfLab02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfLab02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfLab02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfLab02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfLab02().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton buscar;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField ingresoId;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mostrarInfo;
    private javax.swing.JButton pdf;
    private javax.swing.JButton regresar;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}