package Interfaz;

import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.*;
import javax.swing.JOptionPane;

public class Laboratorio04 extends javax.swing.JFrame implements Runnable {

    String hora, minuto, segundo;
    Thread hilo;

    Calendar fecha_actual = new GregorianCalendar();

    public Laboratorio04() {
        initComponents();
        Clases.Usuario4 objetoUsuario = new Clases.Usuario4();
        objetoUsuario.RellenarCombo("usuarios4", "nombre", filtrarNombre);
        objetoUsuario.MostrarSexoCombo(genero);
        diaIngreso.setText(fecha());
        dia.setCalendar(fecha_actual);
        hilo = new Thread(this);
        hilo.start();
        setVisible(true);
        this.setLocationRelativeTo(null);
    }

    public void eliminarInformacion() {
        Clases.Usuario4 borrar = new Clases.Usuario4();
        borrar.Eliminar(WIDTH);
    }

    public void run() {
        Thread current = Thread.currentThread();
        while (current == hilo) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        dia = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        regresarBt = new javax.swing.JButton();
        salirtBt = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        mostrar = new javax.swing.JButton();
        horaIngreso = new javax.swing.JLabel();
        diaIngreso = new javax.swing.JLabel();
        materia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        alumnos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        observacion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        genero = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        horasCombo = new javax.swing.JComboBox<>();
        nombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        filtrarNombre = new javax.swing.JComboBox<>();
        filtrarInfo = new javax.swing.JButton();
        editarInfo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dia.setDateFormatString("yyyy/MM/dd");
        dia.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jPanel6.add(dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 160, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("AYUDA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INGRESE SU NOMBRE:");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BIENVENIDO AL LABORATORIO 03");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        regresarBt.setBackground(new java.awt.Color(0, 0, 51));
        regresarBt.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        regresarBt.setForeground(new java.awt.Color(255, 255, 255));
        regresarBt.setText("REGRESAR");
        regresarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtActionPerformed(evt);
            }
        });
        jPanel6.add(regresarBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        salirtBt.setBackground(new java.awt.Color(0, 0, 51));
        salirtBt.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        salirtBt.setForeground(new java.awt.Color(255, 255, 255));
        salirtBt.setText("SALIR");
        salirtBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirtBtActionPerformed(evt);
            }
        });
        jPanel6.add(salirtBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, -1, -1));

        guardar.setBackground(new java.awt.Color(0, 0, 51));
        guardar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        guardar.setForeground(new java.awt.Color(255, 255, 255));
        guardar.setText("GUARDAR");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jPanel6.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        mostrar.setBackground(new java.awt.Color(0, 0, 51));
        mostrar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        mostrar.setForeground(new java.awt.Color(255, 255, 255));
        mostrar.setText("MOSTRAR");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });
        jPanel6.add(mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, -1, -1));

        horaIngreso.setFont(new java.awt.Font("Segoe UI Black", 1, 10)); // NOI18N
        horaIngreso.setForeground(new java.awt.Color(255, 255, 255));
        horaIngreso.setText("00:00:00");
        jPanel6.add(horaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        diaIngreso.setFont(new java.awt.Font("Segoe UI Black", 1, 10)); // NOI18N
        diaIngreso.setForeground(new java.awt.Color(255, 255, 255));
        diaIngreso.setText("DD/MM/YYYY");
        jPanel6.add(diaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, -1));

        materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiaActionPerformed(evt);
            }
        });
        jPanel6.add(materia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 137, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("INGRESE LA MATERIA:");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ASISTENCIAS DE ESTUDIANTES:");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 20));

        alumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alumnosActionPerformed(evt);
            }
        });
        jPanel6.add(alumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 138, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("OBSERVACIONES DENTRO DEL LABORATORIO:");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        observacion.setColumns(20);
        observacion.setRows(5);
        jScrollPane1.setViewportView(observacion);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 510, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SELECCIONE GÉNERO");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, -1, -1));

        jPanel6.add(genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 133, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SELECCIONE UNA HORA DE CLASE");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 220, -1));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel6.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 130, 0, -1));

        horasCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "07:00-09:00", "09:00-11:00", "11:00-13:00", "14:00-16:00" }));
        jPanel6.add(horasCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 110, -1));

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        jPanel6.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 137, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("SELECCIONE LA FECHA DE LA CLASE");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 240, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DOCENTES INGRESADOS");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        filtrarNombre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        filtrarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarNombreActionPerformed(evt);
            }
        });
        jPanel6.add(filtrarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 140, -1));

        filtrarInfo.setBackground(new java.awt.Color(0, 0, 51));
        filtrarInfo.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        filtrarInfo.setForeground(new java.awt.Color(255, 255, 255));
        filtrarInfo.setText("VER INFORMACIÓN");
        filtrarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarInfoActionPerformed(evt);
            }
        });
        jPanel6.add(filtrarInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 160, -1));

        editarInfo.setBackground(new java.awt.Color(255, 0, 0));
        editarInfo.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        editarInfo.setForeground(new java.awt.Color(255, 255, 255));
        editarInfo.setText("EDITAR");
        editarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarInfoActionPerformed(evt);
            }
        });
        jPanel6.add(editarInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 80, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Inicio2.png"))); // NOI18N
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        // TODO add your handling code here:
        InfLab04 regresa = new InfLab04();
        regresa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mostrarActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
// Obtener los valores de los campos de entrada
        String nombreText = nombre.getText();
        String materiaText = materia.getText();
        String alumnosText = alumnos.getText();
        String observacionText = observacion.getText();

        // Validar que todos los campos estén completos
        if (nombreText.isEmpty() || materiaText.isEmpty() || alumnosText.isEmpty() || observacionText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos.");
            return; // Salir del método si algún campo está vacío
        }

        // Verificar si la cantidad de alumnos ingresada es un número válido
        try {
            int cantidadAlumnos = Integer.parseInt(alumnosText);
            if (cantidadAlumnos > 40) {
                // La cantidad de alumnos supera el límite permitido, mostrar mensaje de advertencia y permitir que el usuario vuelva a ingresar la cantidad
                JOptionPane.showMessageDialog(null, "El laboratorio 04 permite capacidad máxima de 40 alumnos. Ingrese nuevamente la cantidad de alumnos.");
                alumnos.setText(""); // Borrar el valor anterior de la cantidad de alumnos
                alumnos.requestFocus(); // Colocar el foco en el campo de cantidad de alumnos para que el usuario pueda ingresar el valor nuevamente
                return; // Salir del método temporalmente, esperando que el usuario ingrese un valor válido
            }
        } catch (NumberFormatException e) {
            // Se ingresó un valor no numérico en el campo de cantidad de alumnos, mostrar mensaje de error
            JOptionPane.showMessageDialog(null, "Por favor, ingrese un valor numérico válido en el campo de cantidad de alumnos.");
            alumnos.setText(""); // Borrar el valor ingresado
            alumnos.requestFocus(); // Colocar el foco en el campo de cantidad de alumnos para que el usuario pueda ingresar un valor válido
            return; // Salir del método temporalmente, esperando que el usuario ingrese un valor válido
        }

        // Si todos los campos están completos y la cantidad de alumnos es válida, proceder a guardar la información
        Clases.Usuario4 objetoInformacion = new Clases.Usuario4();
        objetoInformacion.agregarInfo(dia, nombre, genero, materia, alumnos, observacion, horasCombo);

        // Limpiar los campos después de guardar la información
        nombre.setText("");
        genero.setSelectedIndex(0);
        materia.setText("");
        alumnos.setText("");
        observacion.setText("");
        id.setText("");
    }//GEN-LAST:event_guardarActionPerformed

    private void salirtBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirtBtActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirtBtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        helpLaboratorio04 helpPr = new helpLaboratorio04();
        helpPr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void regresarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtActionPerformed
        // TODO add your handling code here:
        NEstudiantes estudiantes = new NEstudiantes();
        estudiantes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresarBtActionPerformed

    private void materiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materiaActionPerformed

    private void alumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alumnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alumnosActionPerformed

    private void filtrarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarNombreActionPerformed

    }//GEN-LAST:event_filtrarNombreActionPerformed

    private void filtrarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarInfoActionPerformed
        // TODO add your handling code here:
        // Obtener el nombre seleccionado en el combo
        String nombreSeleccionado = (String) filtrarNombre.getSelectedItem();

        // Verificar si se ha seleccionado un nombre
        if (nombreSeleccionado != null && !nombreSeleccionado.isEmpty()) {
            // Llamar al método para rellenar los campos con la información del usuario por nombre
            Clases.Usuario4 objetoInformacion = new Clases.Usuario4();
            objetoInformacion.rellenarCamposPorNombre(nombreSeleccionado, nombre, genero, materia, alumnos, observacion, horasCombo);
        } else {
            // Mostrar un mensaje indicando que se debe seleccionar un nombre
            JOptionPane.showMessageDialog(null, "Por favor, seleccione un nombre.");
        }
    }//GEN-LAST:event_filtrarInfoActionPerformed

    private void editarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static String fecha() {
        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatofecha.format(fecha);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laboratorio04.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laboratorio04.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laboratorio04.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laboratorio04.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laboratorio04().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alumnos;
    private com.toedter.calendar.JDateChooser dia;
    private javax.swing.JLabel diaIngreso;
    private javax.swing.JButton editarInfo;
    private javax.swing.JButton filtrarInfo;
    private javax.swing.JComboBox<String> filtrarNombre;
    private javax.swing.JComboBox<String> genero;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel horaIngreso;
    private javax.swing.JComboBox<String> horasCombo;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField materia;
    private javax.swing.JButton mostrar;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextArea observacion;
    private javax.swing.JButton regresarBt;
    private javax.swing.JButton salirtBt;
    // End of variables declaration//GEN-END:variables
}
