package Interfaz;

import Interfaz.helpLogin;
import Interfaz.Laboratorio01;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel4 = new javax.swing.JPanel();
        docentePr = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        regresa = new javax.swing.JButton();
        exitPr = new javax.swing.JButton();
        help = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        docentePr.setBackground(new java.awt.Color(0, 0, 51));
        docentePr.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        docentePr.setForeground(new java.awt.Color(255, 255, 255));
        docentePr.setText("INGRESAR");
        docentePr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docentePrActionPerformed(evt);
            }
        });
        jPanel4.add(docentePr, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 100, 30));

        password.setBackground(new java.awt.Color(0, 0, 51));
        password.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel4.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 160, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CONTRASEÑA");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USUARIO");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        usuario.setBackground(new java.awt.Color(0, 0, 51));
        usuario.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        usuario.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 160, -1));

        regresa.setBackground(new java.awt.Color(0, 0, 51));
        regresa.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        regresa.setForeground(new java.awt.Color(255, 255, 255));
        regresa.setText("REGRESAR");
        regresa.setActionCommand("regresar");
        regresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresaActionPerformed(evt);
            }
        });
        jPanel4.add(regresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 100, 30));

        exitPr.setBackground(new java.awt.Color(0, 0, 51));
        exitPr.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        exitPr.setForeground(new java.awt.Color(255, 255, 255));
        exitPr.setText("SALIR");
        exitPr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitPrActionPerformed(evt);
            }
        });
        jPanel4.add(exitPr, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 100, 30));

        help.setBackground(new java.awt.Color(255, 0, 0));
        help.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        help.setForeground(new java.awt.Color(255, 255, 255));
        help.setText("AYUDA");
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        jPanel4.add(help, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 80, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GESTION DE LABORATORIOS");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/LogoP2.png"))); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/FondoAzul.png"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        // TODO add your handling code here:
        helpLogin helpPr = new helpLogin();
        helpPr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_helpActionPerformed

    private void exitPrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitPrActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitPrActionPerformed

    private void docentePrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docentePrActionPerformed
        // TODO add your handling code here:
    String Usuario = usuario.getText();
    String Password = password.getText();
    if (Usuario.isEmpty() || Password.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Llene ambos campos");
    } else {
        if (Usuario.equals("admin")) {
            if (Password.equals("Espe")) {
                // Si tanto el usuario como la contraseña son correctos
                NEstudiantes docenteP = new NEstudiantes();
                docenteP.setVisible(true);
                this.setVisible(false);
            } else {
                // Si el usuario es correcto pero la contraseña es incorrecta
                JOptionPane.showMessageDialog(null, "Contraseña incorrecta");
            }
        } else {
            // Si el usuario es incorrecto
            JOptionPane.showMessageDialog(null, "Usuario incorrecto");
        }
    }
    }//GEN-LAST:event_docentePrActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void regresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresaActionPerformed
        // TODO add your handling code here:
        Principal principal = new Principal();
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton docentePr;
    private javax.swing.JButton exitPr;
    private javax.swing.JButton help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton regresa;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
