/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class NEstudiantes extends javax.swing.JFrame {

    /**
     * Creates new form NEstudiantes
     */
    public NEstudiantes() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        buscaHorario = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cantidadEstudiantes = new javax.swing.JTextField();
        exitPr = new javax.swing.JButton();
        help = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MenuPrincipal = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscaHorario.setBackground(new java.awt.Color(0, 0, 51));
        buscaHorario.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        buscaHorario.setForeground(new java.awt.Color(255, 255, 255));
        buscaHorario.setText("BUSCAR HORARIO");
        buscaHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaHorarioActionPerformed(evt);
            }
        });
        jPanel4.add(buscaHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 150, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("INGRESE LA CANTIDAD MAXIMA DE ESTUDIANTES:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        cantidadEstudiantes.setBackground(new java.awt.Color(0, 0, 51));
        cantidadEstudiantes.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        cantidadEstudiantes.setForeground(new java.awt.Color(255, 255, 255));
        cantidadEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadEstudiantesActionPerformed(evt);
            }
        });
        jPanel4.add(cantidadEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 170, -1));

        exitPr.setBackground(new java.awt.Color(0, 0, 51));
        exitPr.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        exitPr.setForeground(new java.awt.Color(255, 255, 255));
        exitPr.setText("SALIR");
        exitPr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitPrActionPerformed(evt);
            }
        });
        jPanel4.add(exitPr, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 100, 30));

        help.setBackground(new java.awt.Color(255, 0, 0));
        help.setFont(new java.awt.Font("Segoe UI Black", 1, 10)); // NOI18N
        help.setForeground(new java.awt.Color(255, 255, 255));
        help.setText("AYUDA");
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        jPanel4.add(help, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GESTION DE LABORATORIOS");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/LogoP2.png"))); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        MenuPrincipal.setBackground(new java.awt.Color(0, 0, 51));
        MenuPrincipal.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        MenuPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        MenuPrincipal.setText("REGRESAR AL MENÚ");
        MenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPrincipalActionPerformed(evt);
            }
        });
        jPanel4.add(MenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 170, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/FondoAzul.png"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitPrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitPrActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitPrActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        // TODO add your handling code here:
        helpNEstudiantes helpPr = new helpNEstudiantes();
        helpPr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_helpActionPerformed

    private void buscaHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaHorarioActionPerformed
        // Verificar si el campo de texto no está vacío
        if (!cantidadEstudiantes.getText().isEmpty()) {
            // Obtener el texto del campo de texto
            String cantidadEstudiantesText = cantidadEstudiantes.getText();

            // Intentar convertir el texto a un entero
            try {
                int cantidadEstudiantes = Integer.parseInt(cantidadEstudiantesText);

                // Verificar si el número es positivo y no excede 40
                if (cantidadEstudiantes > 0 && cantidadEstudiantes <= 40) {
                    // Realizar el resto del código basado en la cantidad de estudiantes
                    if (cantidadEstudiantes <= 10) {
                        JOptionPane.showMessageDialog(this, "Ha sido asignado al Laboratorio 01");
                        Laboratorio01 lab1 = new Laboratorio01();
                        lab1.setVisible(true);
                        this.setVisible(false);
                    } else if (cantidadEstudiantes > 10 && cantidadEstudiantes <= 20) {
                        JOptionPane.showMessageDialog(this, "Ha sido asignado al Laboratorio 02");
                        Laboratorio02 lab2 = new Laboratorio02();
                        lab2.setVisible(true);
                        this.setVisible(false);
                    } else if (cantidadEstudiantes > 20 && cantidadEstudiantes <= 30) {
                        JOptionPane.showMessageDialog(this, "Ha sido asignado al Laboratorio 03");
                        Laboratorio03 lab3 = new Laboratorio03();
                        lab3.setVisible(true);
                        this.setVisible(false);
                    } else {
                        // Código si la cantidad de estudiantes está entre 31 y 40
                        JOptionPane.showMessageDialog(this, "Ha sido asignado al Laboratorio 04");
                        Laboratorio04 lab4 = new Laboratorio04();
                        lab4.setVisible(true);
                        this.setVisible(false);
                    }
                } else {
                    // Mostrar mensaje de error si el número es negativo, cero o excede 40
                    JOptionPane.showMessageDialog(this, "Ingrese una cantidad válida mayor a 1 y menor a 40");
                }
            } catch (NumberFormatException e) {
                // Capturar la excepción si el texto no puede convertirse a un número entero
                JOptionPane.showMessageDialog(this, "Ingrese una cantidad válida");
            }
        } else {
            // Manejar el caso en que el campo de texto esté vacío
            JOptionPane.showMessageDialog(this, "Ingrese una cantidad");
        }

    }//GEN-LAST:event_buscaHorarioActionPerformed

    private void cantidadEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadEstudiantesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cantidadEstudiantesActionPerformed

    private void MenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPrincipalActionPerformed
        // TODO add your handling code here:
        Principal helpPr = new Principal();
        helpPr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NEstudiantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MenuPrincipal;
    private javax.swing.JButton buscaHorario;
    private javax.swing.JTextField cantidadEstudiantes;
    private javax.swing.JButton exitPr;
    private javax.swing.JButton help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
